mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/apache', '8.1.0'
mod 'puppetlabs/mysql', '13.0.0'
mod 'alexggolovin/lamp', '1.1.0'
mod 'samuelson/dockeragent', '1.0.0'
mod 'puppetlabs/docker', '5.0.0'
mod 'puppetlabs/tomcat', '6.3.0'
mod 'puppet/archive', '6.0.2'
